Pom
Bodhert/protractor-workshop-2019 pull request #4
Opened 2019-01-16 23:13 UTC by Bodhert

understanding how the frameworks uses and works with the page object model

2019-01-18 19:13 UTC, Bodhert commented
![image](https://user-images.githubusercontent.com/14171790/51407888-20d6c300-1b2b-11e9-8d54-758366dc409f.png)

2019-01-21 13:56 UTC, sorregom requested changes
Necesitamos revisar los archivos de la carpeta test, su estructura, comentarios, etc

2019-01-21 13:56 UTC, sorregom commented on src/page/address-step.page.ts
> +    this.proceedToCheckoutButton = $('name="processAddress"');
revisa bien este selector

2019-01-21 13:56 UTC, sorregom commented on src/page/bank-payment.page.ts
> +    this.confirmOrderButton = $('button.btn.btn-default.button-medium');
para aprendizaje cambia el `$` por un `element(by.css( <aqui el selector> ))`

reelmpaza `<>` por el selector

2019-01-21 13:56 UTC, sorregom commented on src/page/personalInformation.page.ts
> +// interface PersonalInformation {
por que esto está comentado?

si no va entonces borralo porfa

2019-01-21 13:56 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    // this.lastNameField = element(by.name('lastname'));
por que todo esto está comentado?

2019-01-21 13:56 UTC, sorregom commented on src/page/product-list.page.ts
> +  private findByProduct(productName: string): ElementFinder {
findProduct me dice que va a encontrar un producto, pero si seguimos Clean Code el método debería tener un nombre más específico, quizas `findProductByName`

2019-01-21 13:56 UTC, sorregom commented on src/page/product-list.page.ts
> +      .filter((item: ElementFinder) =>
item no me dice nada sobre la variable, cambia el nombre de la variable por favor de acuerdo a lo que es la variable

2019-01-21 13:56 UTC, sorregom commented on src/page/shipping-step.page.ts
> +  public async acceptAndContinue(): Promise<void> {
accept que?

2019-01-21 21:00 UTC, sorregom requested changes

2019-01-21 21:00 UTC, sorregom commented on src/page/product-list.page.ts
> +  private findByProductByName(productName: string): ElementFinder {
findProductByName

2019-01-21 21:00 UTC, sorregom commented on src/page/product-list.page.ts
> +      .filter((itemDescription: ElementFinder) =>
esto mismo lo puede hacer el cssContainingText (pero deja la implementacion para que tengas este ejemplo que ya tienes)

2019-01-21 21:00 UTC, sorregom commented on src/page/product-added-modal.page.ts
> +    this.proceedToChekoutButton = $('[style*="display: block;"] .button-container > a.btn.' +
revisa el selector a ver si se puede mejorar

2019-01-21 21:00 UTC, sorregom commented on test/buy-tshirt.spec.ts
> +      const menuContentPage: MenuContentPage = new MenuContentPage();
los const se pueden declarar antes del before

2019-01-21 21:00 UTC, sorregom commented on test/buy-tshirt.spec.ts
> +          describe('and select to pay by bank wire option', () => {
agrega un espacio en blanco

2019-01-21 21:00 UTC, sorregom commented on test/buy-tshirt.spec.ts
> +                beforeAll(async () => {
un it no debe tener un before, se usa sólo para hacer las aserciones

2019-01-24 14:19 UTC, sorregom requested changes
ya casi doc, buen trabajo, unos cambios más y sale

2019-01-24 14:19 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    for (const profession of form.professions) {
mejor separa esto en un método

2019-01-24 14:19 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    if (form.downloadFile) {
y esto

2019-01-24 14:19 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    for (const tool of form.tools) {
y esto en otro método

2019-01-24 14:19 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    for (const commandName of form.commands) {
y esto

2019-01-24 14:19 UTC, sorregom commented on src/page/personalInformation.page.ts
> +    if (form.file) {
esta lógica se puede incluir en el método que estás llamando

2019-01-24 14:19 UTC, sorregom commented on test/locators.spec.ts
> +    it('the page should have the title', async () => {
agregale el then al inicio `Then`

2019-01-24 14:19 UTC, sorregom commented on test/locators.spec.ts
> +    it('the picture should be uploaded', async () => {
y aqui

2019-01-24 14:19 UTC, sorregom commented on test/locators.spec.ts
> +    it('then the file should be downloaded', async () => {
el then debe comenzar con mayuscula

2019-01-24 15:57 UTC, sorregom approved these changes
LGTM niceeee

2019-01-24 16:08 UTC, sorregom requested changes
revisa travis

2019-01-24 16:31 UTC, sorregom approved these changes
OK

2019-01-24 16:37 UTC, merged